name: ystop_mystop
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  pinput: ^2.2.20
  get: ^4.6.5
  qr_code_scanner: ^1.0.1
  logger: ^1.4.0
  get_storage: ^2.1.1
  jwt_decoder: ^2.0.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  ## HOW TO ADD ASSETS
  assets:
    - assets/images/
    - assets/svgs/
  ## HOME TO ADD FONTS
  fonts:
  - family: Graphik
    fonts:
      - asset: assets/fonts/GraphikRegular.otf
  
  - family: GraphikBold
    fonts:
      - asset: assets/fonts/GraphikBold.otf
            